# permissions for end users to edit hives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hive-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hive-operator
    app.kubernetes.io/part-of: hive-operator
    app.kubernetes.io/managed-by: kustomize
  name: hive-editor-role
rules:
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - hives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - hives/status
  verbs:
  - get
