apiVersion: bigdata.kubernetesbigdataeg.org/v1alpha1
kind: Hive
metadata:
  name: hive
spec:      
  size: 1 
  baseImageVersion: "3.1.3-1"
  hiveMetastoreUris: "thrift://hive-svc.default.svc.cluster.local:9083"
# TODO: add connectors to hive image
  dbConnection: 
    userName: "postgres"
    passWord: "postgres"
    url: "jdbc:postgresql://postgresql-svc.default.svc.cluster.local:5432/metastore"
  deployment:
# TODO: comprobar si son necesarias estas variables
    envVar:
      HIVE_DB_NAME: "metastore"   
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
  service:
    thriftPort: 9083
    hiveServerPort: 10000
